#!/bin/bash
umask 0002
if [ "$OPENVPNCFG" = "True" ]; then
    mkdir -p /dev/net
    if [ ! -c /dev/net/tun ]; then
        mknod /dev/net/tun c 10 200
    fi
    exec openvpn --config /config/openvpn.ovpn

    tun0ip=$(ifconfig tun0 | sed -n '2 p' | awk '{print $2}' | cut -d: -f2)
    sed -i "s/\"bind-address-ipv4\": \(.*\)/\"bind-address-ipv4\": \"${tun0ip}\"/g" /config/settings.json
fi

exec /sbin/setuser abc /usr/bin/transmission-daemon -g /config &

